// JWT Middleware - Verify tokens and manage cookies
// Note: JWT tokens are generated by the Auth Service, not BFF
import jwt from 'jsonwebtoken';
import type { Request, Response, NextFunction } from 'express';

const JWT_SECRET = process.env.JWT_SECRET || 'change-this-secret-in-production';
const JWT_COOKIE_NAME = process.env.JWT_COOKIE_NAME || 'flovify_token';

if (JWT_SECRET === 'change-this-secret-in-production') {
  console.warn('⚠️  WARNING: Using default JWT_SECRET. Set a secure secret matching Auth Service!');
}

export interface JwtPayload {
  userId: string;
  email: string;
  role: 'user' | 'admin' | 'super-user';
  iat?: number;
  exp?: number;
}

/**
 * Verify JWT token
 */
export function verifyToken(token: string): JwtPayload {
  try {
    return jwt.verify(token, JWT_SECRET) as JwtPayload;
  } catch (error) {
    throw new Error('Invalid or expired token');
  }
}

/**
 * Set JWT cookie in response
 */
export function setAuthCookie(res: Response, token: string): void {
  res.cookie(JWT_COOKIE_NAME, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production', // HTTPS only in production
    sameSite: 'strict',
    maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days in milliseconds
    path: '/',
  });
}

/**
 * Clear JWT cookie
 */
export function clearAuthCookie(res: Response): void {
  res.clearCookie(JWT_COOKIE_NAME, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'strict',
    path: '/',
  });
}

/**
 * Express middleware to require authentication
 */
export function requireAuth(req: Request, res: Response, next: NextFunction): void {
  const token = req.cookies[JWT_COOKIE_NAME];
  
  if (!token) {
    res.status(401).json({ error: 'Authentication required' });
    return;
  }
  
  try {
    const payload = verifyToken(token);
    req.user = payload; // Attach user to request
    next();
  } catch (error) {
    res.status(401).json({ error: 'Invalid or expired token' });
  }
}

/**
 * Express middleware for optional authentication
 */
export function optionalAuth(req: Request, _res: Response, next: NextFunction): void {
  const token = req.cookies[JWT_COOKIE_NAME];
  
  if (token) {
    try {
      const payload = verifyToken(token);
      req.user = payload;
    } catch {
      // Invalid token, but continue without auth
    }
  }
  
  next();
}

// Extend Express Request type to include user
declare global {
  namespace Express {
    interface Request {
      user?: JwtPayload;
    }
  }
}
