# PostgreSQL database project (private-only)
# - Uses official Postgres image
# - No public exposure; attached to Traefik external Docker network for internal DNS
# - Persistent named volume for data

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    # Optional: bind Postgres to host loopback for local admin tools via SSH tunnel
    # Enable by setting POSTGRES_BIND_LOCALHOST=true
    ports:
      - ${POSTGRES_BIND_LOCALHOST:+127.0.0.1:5432:5432}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - traefik.enable=false
    networks:
      traefik: {}
    restart: unless-stopped

volumes:
  pgdata:
    # Hostinger provides persistent named volumes; this creates one named 'pgdata'

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
