# API private-only deployment (Option A)
# - Attaches API to the existing Traefik network for internal DNS
# - Does NOT expose any public router; traefik.enable=false
# - n8n (on the same network) can call http://api:8000

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}

services:
  api:
    image: ghcr.io/jmnaste/ai-workflow-automation/api:main
    pull_policy: always
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
    labels:
      - traefik.enable=false
    networks:
      traefik:
        aliases:
          - api
    restart: unless-stopped
